### ISSUE TITLE
Writing a Case Analysis Docs (사례분석)

### ISSUE THREAD

**Issue by ehwlfk2** [HappyBeDay/Thanks.com#7]
**1. DeadLine**
9월 5일까지 작성해서 초안 작성

**2. UI, UX** 

**3. Rival Company Analysis**

**Comment by tckim2** [comment]
포인핸드 (http://www.pawinhand.kr/main/html.php?htmid=service/about.html)
동물의집 (https://animalhome.co.kr/)
서울 유기동물 입양센터 (http://saac.kr/?act=main)
도그마루 (https://dmanimal.co.kr/)
유럽펫 (https://ulovepet.co.kr/)
라온보호소(https://laonshelter.co.kr/)
서울동물복지지원센터 (http://animal.seoul.go.kr/index)
댕댕하우스 (http://www.nowonhouse.kr/)
서초동물사랑센터 (https://www.seocho.go.kr/site/animal/main.do)
PetRescue (https://www.petrescue.com.au/)
Pounds Paws (https://www.poundpaws.com.au/)
Pet Smart Charities (https://petsmartcharities.org/)

**Comment by ehwlfk2** [comment]
21.08.30 작성 시작일.
https://docs.google.com/document/d/1m_jY2U0GT1kmx-0HHQBsf3DwhZMo-mfPptb1e6YvMrw/edit?usp=sharing
